- hosts: webservers
  tasks:
    - name: Install basic packages
      become: true
      apt:
        pkg:
          - python-pip
        state: present
        update_cache: yes
    - pip:
        name: docker-py
    - name: Create a Ruby Sinatra API container
      docker_container:
        name: hello-api
        image: franklinyu/sinatra-hello
        ports:
          - 80:9292
        volumes:
          - /tmp/config.ru:/srv/config.ru
